export {
  BUDDYUP_ONBOARDING_MATCH_SPOTLIGHT_V1_KEY as ONBOARDING_MATCH_SPOTLIGHT_V1,
  BUDDYUP_ONBOARDING_WORKSPACE_SPOTLIGHT_V1_KEY as ONBOARDING_WORKSPACE_SPOTLIGHT_V1,
} from "./buddyup-local-storage";
